### ISSUE TITLE
GPU stuff before setting up an OpenGL context

### ISSUE THREAD

**Issue by mjkalyan** [defun-games/claylib#12]
Sometimes we'd like to do something like load a GPU-based object to read some of its slot values during creation of another object _before_ we have an OpenGL context (before `WITH-WINDOW`). This might be the case when setting up a global `*SCENE*`.

But with the context unavailable this will cause an error.

**Comment by mjkalyan** [comment]
Update: trying to iron out the kinks of this approach with eager-future2:
```diff
@@ -101,7 +101,9 @@
              ,sym)))))
 
 (defmacro make-scene (assets objects)
-  (let ((scene (gensym)))
+  (let ((scene (gensym))
+        (objects (loop for (binding val) in objects
+                       collect `(,binding (eager-future2:pcall (lambda () ,val) :lazy)))))
     `(let ((,scene (make-instance 'game-scene)))
        (let* (,@assets ,@objects)
          (declare (ignorable ,@(mapcar #'car (append assets objects))))
@@ -125,6 +127,10 @@
 
 (defmacro with-scene (scene (&key (free :now)) &body body)
   `(progn
+     (maphash (lambda (binding val)
+                "Yield the values of the objects hash table and set them to the yielded values"
+                (setf (gethash binding (objects ,scene)) (eager-future2:yield val)))
+              (objects ,scene))
      (load-scene-all ,scene)
      ,@body
      ,(case free
```

This works for the all-in-one-function examples but not yet with global variables. I just started investigating so it could be something simple. I am just sharing this in the meantime.

**Comment by mjkalyan** [comment]
For clarity's sake: the above approach wraps every object form in a future regardless of whether it tries to load a GPU object, deferring all object initialization until `WITH-SCENE`.

**Comment by mjkalyan** [comment]
> they would either end up getting an error and probably not knowing why, or just clobbering the future, right?

Yes, with this approach we would need to make it clear that game objects are to be changed only by game logic (inside a `WITH-SCENE`) after their initial values are given. On the surface that seems reasonable but it could have unforseen limitations.

> Also, you're going to want to run that `maphash` after `load-scene-all`.

Whoops! Good catch.

**Comment by shelvick** [comment]
> On the surface that seems reasonable but it could have unforseen limitations.

Possible later improvements: Have `make-scene` accept a flag to toggle the use of futures. To get even more granular, change the `make-*` functions to accept a `:lazy` flag to toggle futures for individual objects.

**Comment by shelvick** [comment]
Closing this, as the main issue is fixed, even if we may optimize later.
