### ISSUE TITLE
Certain GEN-MESH-* functions are broken

### ISSUE THREAD

**Issue by shelvick** [defun-games/claylib#16]
In core example 24, we're using `gen-mesh-cube` because `gen-mesh-cylinder` gave me floating point errors. This also occurred with some of the other functions, like `gen-mesh-cone`, `gen-mesh-sphere`, and `gen-mesh-torus`, run directly via `claylib/ll`.

At one point I thought maybe Autowrap was using a double float for pi while Raylib was expecting a single float. After spending more time than I care to admit figuring out how to redefine pi, I was unable to prove this -- most likely a red herring but I couldn't completely rule it out either.

Curious whether it works for you, @mjkalyan. To test, all you have to do is replace the `gen-mesh-cube` call in core example 24 with a `gen-mesh-cylinder` call.

**Comment by mjkalyan** [comment]
Replacing with `(gen-mesh-cylinder 0.2 1 32)` also gives me a floating point error. Sadly I don't have any other insight at this time.

**Comment by shelvick** [comment]
https://github.com/raysan5/raylib/commit/bf07d17cece1421af6227a3e8c823aec58131b36 :thinking:

**Comment by shelvick** [comment]
Fixed in 4.2 branch.
