### ISSUE TITLE
Make colour optional for rectangles

### ISSUE THREAD

**Issue by mjkalyan** [defun-games/claylib#25]
I find it bothersome, and potentially confusing, for `make-rectangle` to force us to set a colour when we may not even use it, as is often the case with source and dest rectangles. It does make sense to force users to set a colour when making rectangles as scene objects, I'm just wondering if there is any way to make this clearer.

Perhaps a `make-bounds-rec`/`make-simple-rec` or some better-named function for creating rectangles you know you'll never draw?
```lisp
(defun make-bounds-rec (x y width height)
  (make-instance 'rectangle
                 :x x :y y
                 :width width :height height))
```

**Comment by shelvick** [comment]
Definitely, and IIRC I did this in one of the GUI examples. It should make a `rl-rectangle` as that directly mirrors Raylib's `Rectangle` and does not require a color. `make-simple-rec` is good, it's more general.

**Comment by mjkalyan** [comment]
Sounds good, I'll add this :)
