### ISSUE TITLE
Support asset re-use across scenes

### ISSUE THREAD

**Issue by mjkalyan** [defun-games/claylib#45]
Currently, `unload-scene-*` functions free both objects and assets associated with a scene. Typically, we'd have our `*assets*` somewhere globally and our `make-scene`s will reference that asset list. When we free one scene using something in `*assets*` we'd need to reload it for another scene to use it. Maybe we need to split `%free` into `%free-assets` and `%free-objects`. Same thing when scene parameters make their way into the mix.

**Comment by mjkalyan** [comment]
`%free :later` or `%free :never` would work, of course, but that would also keep the objects around.

**Comment by shelvick** [comment]
Sure, but let's keep `:free` as a convenience feature to hold onto everything.
