### ISSUE TITLE
Name conflict in dev branch

### ISSUE THREAD

**Issue by simendsjo** [defun-games/claylib#72]
![image](https://user-images.githubusercontent.com/351519/218550720-fd465394-b8a8-4c6a-9c1d-bb6daa605493.png)

**Comment by shelvick** [comment]
We did switch from `cl` to `static-dispatch-cl` as part of enabling static dispatch methods so I would expect this if you're reloading over an existing session. Does this still happen with a fresh Lisp?

**Comment by simendsjo** [comment]
> Does this still happen with a fresh Lisp?

Nope, sorry, should have tested this first.
