### ISSUE TITLE
Unable to load foreign library (LIBRAYSHIM).  

### ISSUE THREAD

**Issue by olegharput** [defun-games/claylib#77]
Unable to load foreign library (LIBRAYSHIM).
  Error opening shared object "/home/oleg/quicklisp/local-projects/claylib/wrap/lib/librayshim.x86_64-pc-linux-gnu.so":
  /home/oleg/quicklisp/local-projects/claylib/wrap/lib/librayshim.x86_64-pc-linux-gnu.so: undefined symbol: GenImageGradientH.
   [Condition of type CFFI:LOAD-FOREIGN-LIBRARY-ERROR]

**Comment by shelvick** [comment]
It looks like Raylib changed the names of a few functions in this commit on May 21: https://github.com/raysan5/raylib/commit/e96dc46d38fcc73cc278ef7a1ad95ce63c6ce989

Claylib expects you to be using the tagged Raylib v4.5 release from March 18. If you're using a system Raylib, it will have to be that same version. At present we are only supporting tagged releases, not keeping up with the (rapidly changing) daily commits.
