### ISSUE TITLE
Can't compile on ECL

### ISSUE THREAD

**Issue by Filipp-Druan** [defun-games/claylib#81]
Then I tried to compile Claylib by ECL:

`$ ecl
;;; Loading "/home/iam/quicklisp/setup.lisp"
;;; Loading #P"/usr/lib/ecl-21.2.1/asdf.fas"
ECL (Embeddable Common-Lisp) 21.2.1 (git:UNKNOWN)
Copyright (C) 1984 Taiichi Yuasa and Masami Hagiya
Copyright (C) 1993 Giuseppe Attardi
Copyright (C) 2013 Juan J. Garcia-Ripoll
Copyright (C) 2018 Daniel Kochmanski
Copyright (C) 2021 Daniel Kochmanski and Marius Gerbershagen
ECL is free software, and you are welcome to redistribute it
under certain conditions; see file 'Copyright' for details.
Type :h for Help.  
Top level in: #<process TOP-LEVEL 0x55f49fcf4f80>.
> (ql:quickload 'claylib)
To load "claylib":
  Load 1 ASDF system:
    claylib
; Loading "claylib"
[package alexandria]..............................
[package alexandria-2]............................
[package babel-encodings].........................
[package babel]...................................
..................................................
[package cffi-sys]................................
[package cffi-callbacks]..........................
[package cffi-features]...........................
[package cffi]....................................
..................................................
[package claylib/wrap]............................
[package claylib/wrap~pristine]...................
..................................................
..................................................
[package claylib/ll]..............................
[package trivial-garbage].........................
[package livesupport].............................
[package closer-mop]..............................
[package closer-common-lisp]......................
[package closer-common-lisp-user].................
[package cl-ppcre]................................
..................................................
[package bordeaux-threads]........................
[package eager-future2]...........................
[package anaphora]................................
[package anaphora-basic]..........................
[package anaphora-symbol].........................
[package arrows]..................................
[package iterate].................................
[package optima.core].............................
[package optima]..................................
[package optima.extra]............................
[package agutil]..................................
[package symbol-munger]...........................
[package collectors-signals]......................
[package collectors]..............................
[package cl-environments.util]....................
[package cl-environments.cltl2]...................
[package cl-environments-cl]......................
[package cl-environments.tools]...................
[package introspect-environment]..................
[package cl-form-types]...........................
[package cl-form-types.walker]....................
..................................................
..................................................
[package closer-environments].....................
[package static-dispatch].........................
[package static-dispatch-cl]......................
..................................................
..................................................
[package org.shirakumo.trivial-extensible-sequences]
[package org.shirakumo.trivial-extensible-sequences.fallback].
.
;;; Internal error:
;;;   ** There is no package with the name SEQUENCE.
Condition of type: COMPILE-FILE-ERROR
COMPILE-FILE-ERROR while compiling #<cl-source-file "trivial-extensible-sequences" "fallback">

Available restarts:

1. (RETRY) Retry compiling #<cl-source-file "trivial-extensible-sequences" "fallback">.
2. (ACCEPT) Continue, treating compiling #<cl-source-file "trivial-extensible-sequences" "fallback"> as having been successful.
3. (RETRY) Retry ASDF operation.
4. (CLEAR-CONFIGURATION-AND-RETRY) Retry ASDF operation after resetting the configuration.
5. (ABORT) Give up on "claylib"
6. (REGISTER-LOCAL-PROJECTS) Register local projects and try again.
7. (RESTART-TOPLEVEL) Go back to Top-Level REPL.

Broken at SI:BYTECODES. [Evaluation of: (QUICKLISP-CLIENT:QUICKLOAD 'CLAYLIB)] In: #<process TOP-LEVEL 0x55f49fcf4f80>.`

How I can fix it?

**Comment by shelvick** [comment]
What happens when you quickload trivial-extensible-sequences on its own?

**Comment by Filipp-Druan** [comment]
Yes.

**Comment by shelvick** [comment]
That wasn't a yes or no question. I'm asking for the _result_ of quickloading trivial-extensible-sequences (on its own).
