### ISSUE TITLE
Invalid initialization arguments in make-texture

### ISSUE THREAD

**Issue by mjkalyan** [defun-games/claylib#9]
```lisp
  (apply #'make-instance 'texture-object
         :asset texture-asset
         :dest (make-instance 'rl-rectangle
                              :x x
                              :y y
                              :width (or width (width texture-asset))
                              :height (or height (height texture-asset)))
         args))
```
As you can see above, `make-texture`, as it is in the asset-rework branch at the moment, gives `:width` and `:height` to the outer `make-instance` for `texture-object` via `args`. `texture-object` does not have `:width`/`:height` so this is an error.

I don't know the cleanest way to solve this since it's undesirable to list out each keyword in place of `args`. I tried that anyway and got an "uneven number of keywords" error - although this is probably a problem on my end. I will investigate it further soon.

**Comment by mjkalyan** [comment]
Ah yes, silly me. I've added `:allow-other-keys t` to `make-texture`.

**Comment by shelvick** [comment]
> silly me

Why silly you? I'm the one who created that bug!
